### ISSUE TITLE
Bug in netstandard 2.0 : XPath2Exception in simple Compile

### ISSUE THREAD

**Issue by Rambalac** [StefH/XPath2.Net#10]
Core2.0 project
`var res=XPath2Expression.Compile("/*/div");` throws
`Wmhelp.XPath2.XPath2Exception: ' at line 1 pos 1'`

**Comment by StefH** [comment]
Does this also happen for NET 4.5.2 or netstandard 1.3 ?

**Comment by StefH** [comment]
Fixed in version XPath2 **1.0.5.1**, please try.

**Comment by StefH** [comment]
@rambalac can you test the new version?

**Comment by StefH** [comment]
@Rambalac Any update?

**Comment by Rambalac** [comment]
Oh, sorry, I did not use GitHub website for some time. Unfortunately I did not use your package. I made my own xpath extension function.

**Comment by StefH** [comment]
Ok. No problem.
