### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by StefH** [StefH/XPath2.Net#12]
I'm also checking if it's easy to create unit-tests which runs all defined tests in xquery-test-suite. In that way I can increase code-coverage and also make a test for this scenario.

**Comment by jzabroski** [comment]
@StefH Where is the xquery-test-suite?

**Comment by StefH** [comment]
Can be found here:
https://dev.w3.org/2006/xquery-test-suite/PublicPagesStagingArea/
