### ISSUE TITLE
Call from PowerShell

### ISSUE THREAD

**Issue by abbgrade** [StefH/XPath2.Net#14]
Hello,

do you ever got it working from PowerShell?

I tried it, but it seems to use XPath1.0 instead of XPath2.0

``` ps
param(
    [string] $Path,
    [string] $XPath2
)

$xmlFile = New-Object System.Xml.XmlDocument
$xmlFile.Load($Path)

Add-Type -Path '.\XPath2.dll' 
$nodes = [Wmhelp.XPath2.XmlNodeExtensions]::XPath2SelectNodes($xmlFile,$XPath2)
```

**Comment by StefH** [comment]
I never used this in powershell. However, how do you see it's using version 2?

**Comment by abbgrade** [comment]
oh .. it works.
I only had an syntay error in the XPath query.

It might be good to add a example to the readme

**Comment by StefH** [comment]
@abbgrade What kind of example do you mean?
