### ISSUE TITLE
Wrong version of XPath.dll is packaged in the 1.0.10 nupkg for net40

### ISSUE THREAD

**Issue by tizubythefizo** [StefH/XPath2.Net#29]
Hi there.

It looks like the net40 folder of the nupkg for version 1.0.10 actually contains the dll for version 1.0.9

This causes the wrong version to be present in .net 4.0+ projects (such as a unit test project), which causes runtime failures when another library (such as XPath2.extensions) expects to find version 1.0.10

In my setup I have a .net standard 2.0 library which references XPath2.extensions. I then have a unit test project for the library (which is .net 4.7.2). I use nuget to load in XPath2.extensions (which in turn adds XPath2). XPath2 extensions is expecting XPath2 v 1.0.10, but 1.0.9 ends up being loaded resulting in a "missing file or assembly" exception at runetime.

![xpath2](https://user-images.githubusercontent.com/14083509/81137199-d0979600-8f12-11ea-860b-44d7525822c6.png)

**Comment by StefH** [comment]
Thanks for noticing this issue.

Can you try preview version from MyGet : XPath2.1.0.11 ?

https://github.com/StefH/XPath2.Net/pull/30

**Comment by tizubythefizo** [comment]
I'm not really sure what myget is.

**Comment by StefH** [comment]
I did upload the 1.0.11 version to MyGet : https://www.myget.org/feed/xpath2/package/nuget/XPath2

See https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions fir example how to use this

**Comment by tizubythefizo** [comment]
Looks like 1.0.11 does build correctly at the proper versions.

**Comment by StefH** [comment]
New official NuGet will be released soon.
