### ISSUE TITLE
Set-up Github actions

### ISSUE THREAD

**Issue by jzabroski** [StefH/XPath2.Net#41]
@StefH It's super easy these days to set-up GitHub Actions 2.0 workflows .  I will submit a PR to do just that.

**Comment by jzabroski** [comment]
Some tasks

- Update WInForms app to .NET 5 https://github.com/jzabroski/XPath2.Net/blob/master/src/XQTSRun/XQTSRun.csproj
- Clean up .netcoreapp2.0
- Clean up test matrix - can be simpler than current Azure Pipelines code

**Comment by StefH** [comment]
Hello @jzabroski,

Thanks for the suggestion, however for now I would like to keep the Azure Pipelines for running the CI.

The other bullet points are a good idea.

Whenever I find more time, I'll check these.
