### ISSUE TITLE
Missing parsing for some html-encoded entity references

### ISSUE THREAD

**Issue by jgilbert2017** [StefH/XPath2.Net#63]
CoreFuncs.cs `NormalizeStringValue` is missing parsing for many entities.  I hit an exception due to `&nbsp;` not being handled.

https://www.w3schools.com/html/html_entities.asp

**Comment by StefH** [comment]
https://github.com/StefH/XPath2.Net/pull/66

**Comment by jgilbert2017** [comment]
my bad, i was looking at the releases list on github.  ty!
